# Generated by Django 5.2.1 on 2025-06-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_repairorder_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('day', models.DateField()),
            ],
            options={
                'unique_together': {('phone', 'ip_address', 'user_agent', 'day')},
            },
        ),
    ]
